# Generated by Django 2.0.7 on 2018-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=256)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood_group', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('city', models.CharField(max_length=100)),
                ('fit_for_donation', models.BooleanField()),
            ],
        ),
    ]
