# Generated by Django 2.0.7 on 2018-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='PWD1234', max_length=256),
        ),
    ]
