# Generated by Django 2.0.7 on 2018-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=1024)),
                ('creationDate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('story', models.CharField(blank=True, max_length=5000, null=True)),
                ('provideCab', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10)),
                ('feedback', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
