# Generated by Django 2.0.7 on 2018-07-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0003_auto_20180725_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodRequests',
            new_name='BloodRequest',
        ),
    ]
