# Generated by Django 2.0.7 on 2018-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0005_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
