# Generated by Django 2.0.7 on 2018-07-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankApp', '0006_auto_20180725_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
    ]
